spring.config.import=optional:file:.env[.properties]

spring.application.name=care-health
server.port=8086

# MySQL Database Connction
spring.datasource.url=${LOCAL_DB_URL}
spring.datasource.username=${LOCAL_DB_USERNAME}
spring.datasource.password=${LOCAL_DB_PASSWORD}

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update

